queue_rules:
  - name: default
    conditions:
      - 'status-success~=Build & Test - Nixpkgs \(ubuntu-.*, rules_haskell, workspace\).*'
      - 'status-success~=Build & Test - Nixpkgs \(ubuntu-.*, rules_haskell, bzlmod\).*'
      - 'status-success~=Build & Test - Nixpkgs \(ubuntu-.*, rules_haskell_tests, workspace\).*'
      - 'status-success~=Build & Test - Nixpkgs \(ubuntu-.*, rules_haskell_tests, bzlmod\).*'
      - 'status-success~=Build & Test - Nixpkgs \(macos-.*, rules_haskell, workspace\).*'
      - 'status-success~=Build & Test - Nixpkgs \(macos-.*, rules_haskell, bzlmod\).*'
      - 'status-success~=Build & Test - Nixpkgs \(macos-.*, rules_haskell_tests, workspace\).*'
      - 'status-success~=Build & Test - Nixpkgs \(macos-.*, rules_haskell_tests, bzlmod\).*'
      - 'status-success~=Build & Test - bindist \(ubuntu-.*, rules_haskell, workspace\).*'
      - 'status-success~=Build & Test - bindist \(ubuntu-.*, rules_haskell, bzlmod\).*'
      - 'status-success~=Build & Test - bindist \(ubuntu-.*, rules_haskell_tests, workspace\).*'
      - 'status-success~=Build & Test - bindist \(ubuntu-.*, rules_haskell_tests, bzlmod\).*'
      - 'status-success~=Build & Test - bindist \(macos-.*, rules_haskell, workspace\).*'
      - 'status-success~=Build & Test - bindist \(macos-.*, rules_haskell, bzlmod\).*'
      - 'status-success~=Build & Test - bindist \(macos-.*, rules_haskell_tests, workspace\).*'
      - 'status-success~=Build & Test - bindist \(macos-.*, rules_haskell_tests, bzlmod\).*'
      - 'status-success~=Build & Test - bindist \(windows-.*, rules_haskell, workspace\).*'
      - 'status-success~=Build & Test - bindist \(windows-.*, rules_haskell, bzlmod\).*'
      - 'status-success~=Build & Test - bindist \(windows-.*, rules_haskell_tests, workspace\).*'
      - 'status-success~=Build & Test - bindist \(windows-.*, rules_haskell_tests, bzlmod\).*'
      - 'status-success~=Build & Test - Cross.*'
      - "status-success=deploy/netlify"

pull_request_rules:
  - name: automatic merge
    conditions:
      - 'status-success~=Build & Test - Nixpkgs \(ubuntu-.*, rules_haskell, workspace\).*'
      - 'status-success~=Build & Test - Nixpkgs \(ubuntu-.*, rules_haskell, bzlmod\).*'
      - 'status-success~=Build & Test - Nixpkgs \(ubuntu-.*, rules_haskell_tests, workspace\).*'
      - 'status-success~=Build & Test - Nixpkgs \(ubuntu-.*, rules_haskell_tests, bzlmod\).*'
      - 'status-success~=Build & Test - Nixpkgs \(macos-.*, rules_haskell, workspace\).*'
      - 'status-success~=Build & Test - Nixpkgs \(macos-.*, rules_haskell, bzlmod\).*'
      - 'status-success~=Build & Test - Nixpkgs \(macos-.*, rules_haskell_tests, workspace\).*'
      - 'status-success~=Build & Test - Nixpkgs \(macos-.*, rules_haskell_tests, bzlmod\).*'
      - 'status-success~=Build & Test - bindist \(ubuntu-.*, rules_haskell, workspace\).*'
      - 'status-success~=Build & Test - bindist \(ubuntu-.*, rules_haskell, bzlmod\).*'
      - 'status-success~=Build & Test - bindist \(ubuntu-.*, rules_haskell_tests, workspace\).*'
      - 'status-success~=Build & Test - bindist \(ubuntu-.*, rules_haskell_tests, bzlmod\).*'
      - 'status-success~=Build & Test - bindist \(macos-.*, rules_haskell, workspace\).*'
      - 'status-success~=Build & Test - bindist \(macos-.*, rules_haskell, bzlmod\).*'
      - 'status-success~=Build & Test - bindist \(macos-.*, rules_haskell_tests, workspace\).*'
      - 'status-success~=Build & Test - bindist \(macos-.*, rules_haskell_tests, bzlmod\).*'
      - 'status-success~=Build & Test - bindist \(windows-.*, rules_haskell, workspace\).*'
      - 'status-success~=Build & Test - bindist \(windows-.*, rules_haskell, bzlmod\).*'
      - 'status-success~=Build & Test - bindist \(windows-.*, rules_haskell_tests, workspace\).*'
      - 'status-success~=Build & Test - bindist \(windows-.*, rules_haskell_tests, bzlmod\).*'
      - 'status-success~=Build & Test - Cross.*'
      - "status-success=deploy/netlify"
      - "#approved-reviews-by>=1"
      - "label=merge-queue"
      - "base=master"
    actions:
      queue:
        name: default
        method: merge

  - name: delete head branch after merge
    conditions:
      - merged
      - closed
    actions:
      delete_head_branch: {}

  - name: remove from merge-queue after merge
    conditions:
      - merged
    actions:
      label:
        remove:
          - "merge-queue"
